# See https://docs.rubocop.org/rubocop/1.54/usage/basic_usage.html and https://github.com/rubocop/rubocop/blob/master/config/default.yml for any additional configuration needs

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{bundle,setup,rails,rake}'
    - 'spec/{rails_helper.rb,spec_helper.rb}'
    - 'vendor/bundle/**/*'

Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition to frozen string literals by default.
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Layout/CommentIndentation:
  Description: Incorrect indentation detected
  Enabled: false

Layout/LineLength:
  Description: Line is too long.
  Max: 199

RSpec/MultipleExpectations:
  Description: Example has too many expectations
  Max: 2

RSpec/ExampleLength:
  Description: Example has too many lines.
  Max: 8