name: Database Ticket
description: Confirmed Database Feature that needs to be implemented
title: "[Database]:"
labels: ["database", "feature"]
assignees: 
  - " "
body:
  - type: textarea
    attributes: 
      label: Is this a new database table or an update to an existing table/schema? 
      description: |
        Leave the :white_check_mark: `:white_check_mark:` to indicate **Yes**, leave the :x: `:x:` to indicate **No**.
      value: |
        | :x: :white_check_mark: New Database Table |  :x: :white_check_mark: Update Existing Database Table |
        | --- | --- |
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Database/Model Description and Requirements
      description: |
        Include:
          - What Type of Database is being used? (PostgreSQL, MySQL, GraphQL, MongoDB)
          - A description/outline of the Database Fields or Changes.
          - Relationship description
          - List of requirements for Schema and Model
      placeholder: |
        Example:
        Create the User Model using PostgreSQL

        1. Needs the following attributes:
           - [ ] First name - String
           - [ ] Last name - String
           - [ ] Email - String
           - [ ] Password Digest - String
           - [ ] Timestamps (created/updated) - DateTime
        2. Setup Password encryption
        3. Add Documentation as and if needed
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything else? Need to be considered or known about this feature?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Do NOT edit this area.
      value: |
        ## General Issue Reminders:

        1. Test for validations.
        2. Test happy / sad / and edge cases
        3. Add Documentation as and if needed

        **Remember:** Use GitHub branch creation for naming
        ![Branch Creation Link Image](https://github.com/Plan-My-Dinner/plan_my_dinner_be/assets/105686836/02a38b44-fe31-4421-8400-546a99e48589))

        - Branches MUST have descriptive names that start with the Issue number. Good examples are: `10-fix-signin-issue` or `22-feature-issue-templates`.

        ![Naming Image](https://github.com/Plan-My-Dinner/plan_my_dinner_be/assets/105686836/661e7e72-2d3a-46a5-8e5e-2b0852e6e6f1)
      render: markdown
    validations:
      required: true
