name: Documentation Issue
description: Current Documentation is not clear, missing info, or needs an update
title: "[Documentation]: "
labels: ["documentation", "triage"]
assignees: 
  - " "
body:
  - type: textarea
    attributes: 
      label: Is this new documentation or an update to existing documentation? 
      description: |
        The update includes Current Documentation is Not Clear
        Leave the :white_check_mark: `:white_check_mark:` to indicate **Yes**, leave the :x: `:x:` to indicate **No**.
      value: |
        | :x: :white_check_mark: New/Missing Documentation |  :x: :white_check_mark: Update Documentation |
        | --- | --- |
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Documentation Description and Requirements
      description: A description of the documentation issue and task list of requirements.
      placeholder: |
        Example:
         -[ ] Create an About Section that gives a brief description of what the app is for
         -[ ] Add applicable Badges for current Tech and CI/CD
         -[ ] Set up instructions for new collaborators
         -[ ] Info about the API we are using
         -[ ] Table of contents
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything else? Need to be considered or known about this feature?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Do NOT edit this area.
      value: |
        ## General Issue Reminders:

        **Remember:** Use GitHub branch creation for naming

        ![Branch Creation Link Image](https://github.com/Plan-My-Dinner/plan_my_dinner_be/assets/105686836/02a38b44-fe31-4421-8400-546a99e48589)

        - Branches MUST have descriptive names that start with the Issue number. Good examples are: `10-fix-signin-issue` or `22-feature-issue-templates`.

        ![Naming Image](https://github.com/Plan-My-Dinner/plan_my_dinner_be/assets/105686836/661e7e72-2d3a-46a5-8e5e-2b0852e6e6f1)
    validations:
      required: true
