name: Other Feature Ticket
description: Adding or Changing Model logic or something else that does not fit other feature types
title: "[Feature]:"
labels: ["feature"]
assignees: 
  - " "
body:
  - type: markdown
    attributes:
      value: |
        # Only use this form if NO other template fits the Feature Needed.
        ### If this is a feature suggestion or __you__ are not a collaborator on this repo, please use a Blank Issue.
        This should only be used for Confirmed Features and be assigned to a sprint.
  - type: textarea
    attributes: 
      label: Is this new or an update to existing code/logic? 
      description: |
        Leave the :white_check_mark: `:white_check_mark:` to indicate **Yes**, leave the :x: `:x:` to indicate **No**.
      value: |
        | :x: :white_check_mark: New Logic/Code |  :x: :white_check_mark: Update Current Logic/Code |
        | --- | --- |
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description and Requirements
      description: "A description of the feature, why it's needed, and a task list of requirements."
      placeholder: |
        Example:
        Title formatting Logic:
         - Add functionality to Capitalize only the first letter of each word in a Recipe's title
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the Expected Behavior?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        1. If this is a change/update, indicate the reason for the change.
        2. Anything else? Need to be considered or known about this feature? Concerns?
        3. Links to useful references, implementation info, research docs, pictures/images...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Do NOT edit this area.
      value: |
        ## General Issue Reminders:

        **Remember:** Use GitHub branch creation for naming
        
        ![Branch Creation Link Image](https://github.com/Plan-My-Dinner/plan_my_dinner_be/assets/105686836/02a38b44-fe31-4421-8400-546a99e48589)

        - Branches MUST have descriptive names that start with the Issue number. Good examples are: `10-fix-signin-issue` or `22-feature-issue-templates`.

        ![Naming Image](https://github.com/Plan-My-Dinner/plan_my_dinner_be/assets/105686836/661e7e72-2d3a-46a5-8e5e-2b0852e6e6f1)
      render: markdown
    validations:
      required: true
