# https://github.com/marketplace/actions/auto-assign-issues-prs for reference of action set-up 
name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.TEAM_ACTIONS_PAT }}
          reviewers: |
            Plan-My-Dinner/backend-team
