# Action Reference documentation https://github.com/marketplace/actions/simplecov-check
name: "Code Coverage"
on:
  workflow_run:
    workflows: ["CI Testing"]
    types: [requested]
    branches: ["main"]
jobs:
  coverage:
    name: SimpleCov Coverage Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage 

      - name: Check coverage
        uses: vigetlabs/simplecov-check@v1.0
        with:
          minimum_coverage: 90
          coverage_path: coverage/.last_run.json
