# Action Reference documentation https://github.com/marketplace/actions/simplecov-check
name: "Code Coverage"
on:
  workflow_run:
    workflows: ["CI Testing"]
    types: [completed]
#     branches: ["main"]
jobs:
  coverage:
    name: SimpleCov Coverage Report
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage-report
          path: coverage
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage
      - name: Check coverage
        uses: vigetlabs/simplecov-check@1.0
        with:
          minimum_coverage: 90
          coverage_path: coverage/.last_run.json
