# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI Testing"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          bundler-cache: true
      - name: Bundle install
        run:
          bundle install
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bundle exec rails db:reset #db:drop, db:setup (db:create, db:schema:load, db:seed)
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage-report
          path: coverage
<<<<<<< HEAD
=======
  coverage:
  # Action Reference documentation https://github.com/marketplace/actions/simplecov-check
    name: SimpleCov Coverage Report
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ success() }}
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage 
      - name: Check coverage
        uses: vigetlabs/simplecov-check@1.0
        with:
          minimum_coverage: 90
          coverage_path: coverage/.last_run.json
>>>>>>> 90d6f7d13a7c60a474e627832f27a08ac795ac33

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
#       - name: Security audit dependencies
#         run: bin/bundler-audit --update
      - name: Run Brakerman for security vulnerabilities
        run: bundle exec brakeman --color
      - name: Run RuboCop
        run: bundle exec rubocop

  # deploy:
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  #   needs: [test, lint]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - run: flyctl deploy --remote-only
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}